# Business Problem - Predict the Price of Bangalore House
## using Linear Regression - Supervised Machine Learning Algorithm

In [ ]:
# Load Libraries
import pandas as pd
import numpy as np

In [ ]:
# Load DataSet
df1 = pd.read_csv('/content/Bengaluru_House_Data.csv')
df1.head()

area_type   availability  ... balcony   price
0  Super built-up  Area         19-Dec  ...     1.0   39.07
1            Plot  Area  Ready To Move  ...     3.0  120.00
2        Built-up  Area  Ready To Move  ...     3.0   62.00
3  Super built-up  Area  Ready To Move  ...     1.0   95.00
4  Super built-up  Area  Ready To Move  ...     1.0   51.00

[5 rows x 9 columns]

In [ ]:
df1.shape

(13320, 9)

In [ ]:
df1.groupby('area_type')['area_type'].agg('count')

area_type
Built-up  Area          2418
Carpet  Area              87
Plot  Area              2025
Super built-up  Area    8790
Name: area_type, dtype: int64

In [ ]:
# Remove unnecessary columns
df2 = df1.drop(['area_type', 'society', 'balcony', 'availability'], axis='columns')
df2.head()

location       size total_sqft  bath   price
0  Electronic City Phase II      2 BHK       1056   2.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2               Uttarahalli      3 BHK       1440   2.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                  Kothanur      2 BHK       1200   2.0   51.00

In [ ]:
# Identify the null value
df2.isnull().sum()

location       1
size          16
total_sqft     0
bath          73
price          0
dtype: int64

In [ ]:
df3 = df2.dropna()
df3.isnull().sum()

location      0
size          0
total_sqft    0
bath          0
price         0
dtype: int64

In [ ]:
df3.shape

(13246, 5)

In [ ]:
# Finding the unique values and get only numeric value
df3['size'].unique()

array(['2 BHK', '4 Bedroom', '3 BHK', '4 BHK', '6 Bedroom', '3 Bedroom',
       '1 BHK', '1 RK', '1 Bedroom', '8 Bedroom', '2 Bedroom',
       '7 Bedroom', '5 BHK', '7 BHK', '6 BHK', '5 Bedroom', '11 BHK',
       '9 BHK', '9 Bedroom', '27 BHK', '10 Bedroom', '11 Bedroom',
       '10 BHK', '19 BHK', '16 BHK', '43 Bedroom', '14 BHK', '8 BHK',
       '12 Bedroom', '13 BHK', '18 Bedroom'], dtype=object)

In [ ]:
dummies = pd.get_dummies(df3) 
dummies

bath   price  ...  total_sqft_998  total_sqft_999
0       2.0   39.07  ...               0               0
1       5.0  120.00  ...               0               0
2       2.0   62.00  ...               0               0
3       3.0   95.00  ...               0               0
4       2.0   51.00  ...               0               0
...     ...     ...  ...             ...             ...
13315   4.0  231.00  ...               0               0
13316   5.0  400.00  ...               0               0
13317   2.0   60.00  ...               0               0
13318   4.0  488.00  ...               0               0
13319   1.0   17.00  ...               0               0

[13246 rows x 3404 columns]

In [ ]:
df4 = pd.get_dummies(df3, drop_first = True)

In [ ]:
# df5 = df4[['bath',	'price',	'location_ Banaswadi',	'location_ Basavangudi',	'location_ Bhoganhalli',
# 'location_ Devarabeesana Halli', 'total_sqft_957',	'total_sqft_958',	'total_sqft_959',	'total_sqft_960']]
# df6 = df5.fillna(df5.mean())
# df6

In [ ]:
# df6.shape

# Apply One Hot Encoding

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
oh_enc = OneHotEncoder(sparse = False)

In [ ]:
oh_enc_arr = oh_enc.fit_transform(df3[['location','size','total_sqft']])
oh_enc_arr

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
dummies.keys()

Index(['bath', 'price', 'location_ Anekal', 'location_ Banaswadi',
       'location_ Basavangudi', 'location_ Bhoganhalli',
       'location_ Devarabeesana Halli', 'location_ Devarachikkanahalli',
       'location_ Electronic City', 'location_ Mysore Highway',
       ...
       'total_sqft_990', 'total_sqft_991', 'total_sqft_992', 'total_sqft_993',
       'total_sqft_994', 'total_sqft_995', 'total_sqft_996', 'total_sqft_997',
       'total_sqft_998', 'total_sqft_999'],
      dtype='object', length=3404)

In [ ]:
# convert into dataframe
oh_enc_df = pd.DataFrame(dummies)
oh_enc_df

bath   price  ...  total_sqft_998  total_sqft_999
0       2.0   39.07  ...               0               0
1       5.0  120.00  ...               0               0
2       2.0   62.00  ...               0               0
3       3.0   95.00  ...               0               0
4       2.0   51.00  ...               0               0
...     ...     ...  ...             ...             ...
13315   4.0  231.00  ...               0               0
13316   5.0  400.00  ...               0               0
13317   2.0   60.00  ...               0               0
13318   4.0  488.00  ...               0               0
13319   1.0   17.00  ...               0               0

[13246 rows x 3404 columns]

In [ ]:
X = oh_enc_df.drop('price', axis=1)
y = oh_enc_df['price']
 
print('Shape of X = ', X.shape)
print('Shape of y = ', y.shape)

Shape of X =  (13246, 3403)
Shape of y =  (13246,)


## Splitting the DataSet Into Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 51)
print('Shape of X_train = ', X_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', X_test.shape)
print('Shape of y_test = ', y_test.shape)

Shape of X_train =  (10596, 3403)
Shape of y_train =  (10596,)
Shape of X_test =  (2650, 3403)
Shape of y_test =  (2650,)


In [ ]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train) 
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
# Linear Regression - ML Model Training
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
lr.coef_

array([ 5.54622036e+00, -5.07122941e+14, -4.02002322e+12, ...,
       -4.88975230e+12, -4.88975230e+12, -8.46850002e+12])

In [ ]:
lr.intercept_

111.35472341121758

## Predict the value of Home and Test

In [ ]:
X_test[0, :]

array([ 2.5857092 , -0.00971515, -0.00971515, ..., -0.00971515,
       -0.00971515, -0.01682872])

In [ ]:
lr.predict([X_test[0, :]])

array([165.69920093])

In [ ]:
lr.predict(X_test)

array([ 164.7593865 ,   78.5406365 ,   79.8531365 , ...,    8.9468865 ,
       1064.079699  ,   -1.13795728])

In [ ]:
y_test

3794     160.00
10425     60.00
10533     65.00
8309      42.79
1946     110.00
          ...  
1985      93.00
9585      85.00
7282      66.00
2885     400.00
5892      55.00
Name: price, Length: 2650, dtype: float64

In [ ]:
# compare Accuracy
lr.score(X_test, y_test)

-1.855704356435457e+26

# Implementing Ridge and Lasso Regression
## Ridge and Lasso is used for Improve accuracy of our model.

In [ ]:
from sklearn.linear_model import Ridge,Lasso

In [ ]:
ls = Lasso()

ls.fit(X_train,y_train)

ls.score(X_test, y_test)

0.3916823269009587

In [ ]:
# Increase the value of alpha for improving accuracy

rd2 = Ridge(alpha = 2)

rd2.fit(X_train,y_train)

rd2.score(X_test, y_test)

0.2869321605732861

In [ ]:
# Increase the value of alpha for improving accuracy

ls2 = Lasso(alpha = 2)

ls2.fit(X_train,y_train)

ls2.score(X_test, y_test)

0.437481076518649

# Model Evaluation
# Root Mean Square Error( Is used for calculating error in our model.)

In [ ]:
y_pred = lr.predict(X_test)
y_pred

array([ 164.7593865 ,   78.5406365 ,   79.8531365 , ...,    8.9468865 ,
       1064.079699  ,   -1.13795728])

In [ ]:
from sklearn.metrics import mean_squared_error
import numpy as np

In [ ]:
mse =  mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)

print('MSE = ', mse)
print('RMSE = ', rmse)

MSE =  5.023387008223033e+30
RMSE =  2241291370666258.0
